=== plutomonth/Jdptool/src/resources/net/sf/jdptool/resources/jdp-config_1_0.dtd
<!--
     DTD for the Jdptool config File

     To support validation of your configuration file, include the following
     DOCTYPE element at the beginning (after the "xml" declaration):

     <!DOCTYPE jdp-config PUBLIC
       "-//SourceForge net//DTD Jdptool config 1.0//EN"
       "http://www.future.org/dtds/jdp-config_1_0.dtd">
-->

<!-- ========== Defined Types ============================================= -->

<!-- A "Boolean" is the string representation of a boolean (true or false)
     variable.
-->
<!ENTITY % Boolean "(true|false|yes|no)">

<!-- An "Integer" is a character string consisting solely of numeric digits,
     optionally preceeded by a minus sign, that can be converted to a
     32-bit integer.
-->
<!ENTITY % Integer "CDATA">


<!-- A "Time" time format date, such as yyyy-mm-dd hh:MM:ss.
-->
<!ENTITY % Time "CDATA">


<!-- A "StepType" is the string representation of a step
-->
<!ENTITY % StepType "(into|return|over)">

<!-- A "ClassName" is the fully qualified name of a Java class that is
     instantiated to provide the functionality of the enclosing element.
-->
<!ENTITY % ClassName "CDATA">


<!-- A "MethodName" is the identifier of a method name of class.
-->
<!ENTITY % MethodName "CDATA">


<!-- A "PropName" is the name of a JavaBeans property, and must begin with
     a lower case letter and contain only characters that are legal in a
     Java identifier.
-->
<!ENTITY % FieldName "CDATA">


<!-- A "ScopeType" is the variable scope in the class, field is the member
	 variable of class, static is static member of class, local is local
	 variable in a method
-->
<!ENTITY % ScopeType "(field|static|local)">


<!-- A "WatchType" is the notification of diffrent actions to field. "access"
	 is relate to AccessWatchpointEvent/Request; "modify" is realte to 
	 ModificationWatchpointEvent/Request. It follow JDI field's request/event.
-->
<!ENTITY % WatchType "(access|modify|both)">

<!-- =================== Top Level Elements =============================== -->
<!-- The "jdp-config" element is the root of the configuration file
     hierarchy, and contains nested elements for all of the other
     configuration settings.

     name       The identifier of jdp-config
-->
<!ELEMENT jdp-config	(recorder, runner+, plugin*) >
<!ATTLIST jdp-config    	name		CDATA			#IMPLIED>


<!-- The "recorder" element is the configuration of recorder object
	 which should be used by all runners to track debug information.
	 The following attributes are defined:
	 
     name       The identifier of recorder
     
	 class      The detail class implements Recorder interface
-->
<!ELEMENT recorder (param*) >
<!ATTLIST recorder			name		CDATA		    #REQUIRED>
<!ATTLIST recorder			class		%ClassName;		#REQUIRED>

<!-- The "runner" element is the configuration of runner object.
	 It is the main component/service in Jdptool; The following
     attributes are defined:
     
     name       The identifier of runner
	 
	 class      The detail class implements Runner interface
-->
<!ELEMENT runner (param*) >
<!ATTLIST runner			name		CDATA		    #REQUIRED>
<!ATTLIST runner			class		%ClassName;		#REQUIRED>

<!-- The "plugin" element is the configuration of plugin component
	 which should be used by all runners to track debug information.
	 The following attributes are defined:
	 
     name       The identifier of plugin 
     
	 class      The detail class implements plugin interface
-->
<!ELEMENT plugin (param*) >
<!ATTLIST plugin			name		CDATA		    #REQUIRED>
<!ATTLIST plugin			class		%ClassName;		#REQUIRED>

<!-- The "param" element is the configuration of parameter which
	 should be used by all element needed, The following attributes
	 are defined:
	 
	 name       The name of the key
	 
	 value      The value of the key
-->
<!ELEMENT param EMPTY>
<!ATTLIST param				name		%FieldName;		#REQUIRED>
<!ATTLIST param				value		CDATA			#REQUIRED>

=== plutomonth/Jdptool/runtime/conf/default-jdp-config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!DOCTYPE jdp-config PUBLIC
       "-//SourceForge net//DTD Jdptool config 1.0//EN"
       "http://www.future.org/dtds/jdp-config_1_0.dtd">       
<!--
	This is profiler configuration file used for test
	API of profiler filter
-->

<jdp-config name="default">

    <recorder name="FileRecorder" class="net.sf.jdptool.recorder.FileRecorder" >
        <param name="filepath" value="${jdptool.home}/runtime/logs"/>
    </recorder>
    
    <runner name="snapshot" class="net.sf.jdptool.SnapshotRunner">
        <param name="interval" value="10000" />
        <param name="excludes"  value="java.*;javax.*;sun.*;org.apache.*"/>
    </runner>
    
    <runner name="EventHandler" class="net.sf.jdptool.EventHandlerRunner">
        <param name="excludes"  value="java.*;javax.*;sun.*;org.apache.*"/>
        <param name="filter"  value="${jdptool.home}/runtime/conf/default-jdp-filter.xml"/>
    </runner>
  
	<plugin name="FilterPlugin" class="net.sf.jdptool.filter.FilterPlugin">
	    <param name="filepath" value="${jdptool.home}/runtime/conf/default-jdp-filter.xml" />
	</plugin>
	
</jdp-config>
